# Generated by Django 3.1.4 on 2020-12-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='fileUpload',
            field=models.FileField(upload_to='file/2020/12'),
        ),
    ]
